<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <h5 class="m-0">
                        <a href="{{ route('reportsfinancialcash_flow_report') }}"> Cash Flow Reports </a>
                    </h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid bg-light">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group bg-light p-2 border border-secondary">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="row">
                                    <div class="col-md-5">
                                        <livewire:date-input name="DATE_FROM" titleName="Date Start"
                                            wire:model.live='DATE_FROM' :isDisabled="false" />
                                    </div>
                                    <div class="col-md-5">
                                        <livewire:date-input name="DATE_TO" titleName="Date End"
                                            wire:model.live='DATE_TO' :isDisabled="false" />
                                    </div>
                                    <div class='col-md-12 mt-1'>
                                        <div class="form-group">
                                            <button class="btn btn-danger btn-xs w-25"
                                                wire:click='generate()'>Generate</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">

                            </div>
                            <div class="col-md-4">
                                <div class="row">
                                    <div class="col-md-8">
                                        <label class="text-xs mt-1">Modify</label> <input wire:model.live='modify'
                                            type='checkbox' class="text-xs" />
                                    </div>
                                    <div class="col-md-4">
                                        <div class="mt-0">
                                            <label class="text-xs ">Location:</label>
                                            <select
                                                @if (Auth::user()->locked_location) style="opacity: 0.5;pointer-events: none;" @endif
                                                name="location" wire:model.live='LOCATION_ID'
                                                class="form-control form-control-sm text-xs ">
                                                <option value="0"> All Location</option>
                                                @foreach ($locationList as $item)
                                                    <option value="{{ $item->ID }}"> {{ $item->NAME }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-12 col-sm-12 col-md-12  col-lg-8" style="max-height: 80vh; overflow-y: auto;">
                    <table class="table table-sm  table-hover ">
                        <thead class="bg-sky h1">
                            <tr>
                                <th>Statement of Cash Flows</th>
                                <th class="text-right">Amount</th>
                            </tr>
                        </thead>
                        <tbody class="h1">
                            <tr>
                                <td> Cash Flows from Operating Activities </td>
                                <td> </td>
                            </tr>
                            <tr>
                                <td> Cash Flow Before WC Changes</td>
                                <td> </td>
                            </tr>
                            <tr>
                                <td> Cash Generated By/(Used in) Operating Activities</td>
                                <td> </td>
                            </tr>
                            <tr>
                                <td> Net Cash from Operating Activities</td>
                                <td> </td>
                            </tr>
                            <tr>
                                <td> Cash Flow from Investing Activities</td>
                                <td> </td>
                            </tr>
                            <tr>
                                <td> Cash Generated By/(Used In) Investing Activities</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td> Cash Flow from Financing Activities</td>
                                <td></td>
                            </tr>

                            <tr>
                                <td>Cash Generated By/(Used In) Financing Activities</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td> Cash at the End of Period</td>
                                <td></td>
                            </tr>
                            @if ($modify)
                                <tr>
                                    <td>
                                        <a href="#" class="btn btn-xs btn-success">
                                            <i class="fa fa-plus" aria-hidden="true"></i> Header
                                        </a>
                                    </td>
                                    <td></td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>
