<?php

namespace App\Livewire\FinancialReport;

use App\Services\CashFlowServices;
use App\Services\DateServices;
use App\Services\FinancialStatementServices;
use App\Services\LocationServices;
use App\Services\UserServices;
use Livewire\Attributes\On;
use Livewire\Attributes\Title;
use Livewire\Component;

#[Title('Cash Flow Report')]
class CashFlowReport extends Component
{


    public float $TOTAL_AFTER_NEW_HEADER = 0;
    public int $YEAR;
    public int $MONTH;
    public  $modify = false;
    public int $LOCATION_ID;
    public $locationList = [];
    public $monthList = [];

    public $headerList = [];
    public $dataList = [];

    private $financialStatementServices;
    private $locationServices;
    private $userServices;
    private $dateServices;
    private $cashFlowServices;
    public function boot(
        FinancialStatementServices $financialStatementServices,
        LocationServices $locationServices,
        UserServices $userServices,
        DateServices $dateServices,
        CashFlowServices $cashFlowServices,
    ) {
        $this->financialStatementServices = $financialStatementServices;
        $this->locationServices = $locationServices;
        $this->userServices = $userServices;
        $this->dateServices = $dateServices;
        $this->cashFlowServices = $cashFlowServices;
    }
    public function mount()
    {



        $this->monthList = $this->dateServices->MonthList();
        $this->locationList = $this->locationServices->getList();

        $this->YEAR = $this->dateServices->NowYear();
        $this->MONTH = $this->dateServices->NowMonth();

        $this->LOCATION_ID = $this->userServices->getLocationDefault();
    }

    private function AcctFormat(float $AMOUNT)
    {
        if ($AMOUNT >= 0) {
            return  (string) number_format($AMOUNT, 2);
        } else {
            $newText = str_replace("-", "", $AMOUNT);
            return  (string) "(" . number_format($newText, 2) . ")";
        }
    }
    public function generate()
    {
        $BASE_DATE = $this->YEAR . '-' . $this->MONTH . '-15';
        $FIRST_DAY = $this->dateServices->GetFirstDay_Month($BASE_DATE);
        $LAST_DAY =  $this->dateServices->GetLastDay_Month($BASE_DATE);


        $NET_INCOME = (float) $this->financialStatementServices->getTotalNetIncome($FIRST_DAY, $LAST_DAY, $this->LOCATION_ID);
        $DEPRECIATION_EXP = (float) $this->financialStatementServices->getIncomeStatementAccountByIDSum($FIRST_DAY, $LAST_DAY, $this->LOCATION_ID, 32, false);
        $INTEREST_EXP = (float) $this->financialStatementServices->getIncomeStatementAccountByIDSum($FIRST_DAY, $LAST_DAY, $this->LOCATION_ID, 31, false);
        $IMPAIRMENT_LOSS = (float) $this->financialStatementServices->getIncomeStatementAccountByIDSum($FIRST_DAY, $LAST_DAY, $this->LOCATION_ID, 31, false);
        $DISPOSAL_ASSET = 0;
        $INCOME_TAX_EXP = 0;

        $CASH_FLOW_BEFORE_WC_CHANGE = 0;
        $AMOUNT  = 0;
        $this->dataList = [];

        $this->AddLine('OPERATING ACTIVITIES', 'text-primary');
        $this->AddLine('Income', 'text-info', $this->AcctFormat($NET_INCOME));

        $this->AddLine('Adjustments for:');
        $this->AddLine('+ Depreciation', 'text-info', $this->AcctFormat($DEPRECIATION_EXP));
        $this->AddLine('+ Interest Expense', 'text-info', $this->AcctFormat($INTEREST_EXP));
        $this->AddLine('+ Impairment Losses', 'text-info', $this->AcctFormat($IMPAIRMENT_LOSS));
        $this->AddLine('+ Loss / (Gain) on Disposal of Assets', 'text-info', $this->AcctFormat($DISPOSAL_ASSET));
        $this->AddLine('+ Income Tax Expense', 'text-info', $this->AcctFormat($INCOME_TAX_EXP));

        $this->AddLine('Cash Flow Before WC Changes', '', $this->AcctFormat($CASH_FLOW_BEFORE_WC_CHANGE), true);

        $this->AddLine('Working Capital Changes:');
        $this->AddLine('+- in Trade & Other Receivables', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('+- in Other Current Assets', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('+- in Other Non-Current Assets', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('+- in Trade and Other Payables', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Cash Generated By/(Used in) Operating Activities', 'text-primary', $this->AcctFormat($AMOUNT), true);
        $this->AddLine('Income Tax Paid', 'text-info', $this->AcctFormat($AMOUNT));


        $this->AddLine('Net Cash from Operating Activities', 'text-primary', $this->AcctFormat($AMOUNT), true);
        $this->AddSpace();
        $this->AddLine('INVESTING ACTIVITIES', 'text-primary');
        $this->AddLine('Advances to Related Parties', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Proceeds from Sale / (Purchase) of Property, Plant and Equipment', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Cash Generated By/(Used In) Investing Activities', 'text-primary', $this->AcctFormat($AMOUNT), true);
        $this->AddSpace();

        $this->AddLine('FINANCING ACTIVITIES', 'text-primary');
        $this->AddLine('Advances from Related Parties', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Proceeds from The Issuance of Capital Stock/Deposit For Future Stock Subscription', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Lease Liability', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Proceeds from Loan Availments (Payment of Loans)', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Payments of Dividends', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Interest Expense Paid', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Cash Generated By/(Used In) Financing Activities', 'text-primary', $this->AcctFormat($AMOUNT), true);
        $this->AddSpace();

        $this->AddLine('Increase / (Decrease) in Cash', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Cash at Beginning of Period', 'text-info', $this->AcctFormat($AMOUNT));
        $this->AddLine('Cash at the End of Period', 'text-primary', $this->AcctFormat($AMOUNT), true);
    }

    private function AddLine(string $name,  string $strClass = "", string $amount = '', bool $underline = false)
    {
        $data = [
            'name'      => $name,
            'amount'    => $amount,
            'class'     => $strClass,
            'underline' => $underline
        ];

        $this->dataList[] = $data;
    }
    private function AddSpace()
    {
        $data = [
            'name'      => '',
            'amount'    => '',
            'class'     => '',
            'underline' => false
        ];
        $this->dataList[] = $data;
    }

    public function render()
    {

        return view('livewire.financial-report.cash-flow-report');
    }
}
