<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hemodialysis extends Model
{
    use HasFactory;

    protected $table = 'hemodialysis';
    protected $primaryKey = 'ID';
    public $timestamps = false;
    protected $fillable = [
        'ID',
        'RECORDED_ON',
        'DATE',
        'CODE',
        'CUSTOMER_ID',
        'LOCATION_ID',
        'USER_ID',
        'NO_OF_TREATMENT',
        'MACHINE_NO',
        'PRE_WEIGHT',
        'PRE_BLOOD_PRESSURE',
        'PRE_HEART_RATE',
        'PRE_O2_SATURATION',
        'PRE_TEMPERATURE',
        'POST_WEIGHT',
        'POST_BLOOD_PRESSURE',
        'POST_HEART_RATE',
        'POST_O2_SATURATION',
        'POST_TEMPERATURE',
        'UF_GOAL',
        'BFR',
        'DFR',
        'DURATION',
        'DIALYZER',
        'RE_USE_NO',
        'HERAPIN',
        'FLUSHING',
        'SC_MACHINE_TEST',
        'SC_SECURED_CONNECTION',
        'SC_SALINE_LINE_DOUBLE_CLAMP',
        'SC_CONDUCTIVITY',
        'SC_DIALYATE_TEMP',
        'SC_RESIDUAL_TEST_NIGATIVE',
        'DB_STANDARD_HCOA',
        'DB_ACID',
        'DB_NA_MEG_L',
        'DB_KPLUS_MEG_L',
        'DB_CAPPLS_MEG_L',
        'ACCESS_TYPE_FISTUAL',
        'ACCESS_TYPE_GRAFT',
        'ACCESS_TYPE_R',
        'ACCESS_TYPE_L',
        'BRUIT_STRONG',
        'BRUIT_WEAK',
        'BRUIT_ABSENT',
        'THRILL_STRONG',
        'THRILL_WEAK',
        'THRILL_ABSENT',
        'HEMOTOMA_PRESENT',
        'HEMOTOMA_ABSENT',
        'ACCESS_OTHERS',
        'CVC_SUBCATH',
        'CVC_JUGCATH',
        'CVC_FEMCATH',
        'CVC_PERMCATH',
        'CVC_LOCATION_R',
        'CVC_LOCATION_L',
        'CVC_A_GOOD_FLOW',
        'CVC_A_WRESISTANT',
        'CVC_A_CLOTTED_NON_PATENT',
        'CVC_v_GOOD_FLOW',
        'CVC_v_WRESISTANT',
        'CVC_v_CLOTTED_NON_PATENT',
        'PRE_ASSIST_AMBULATORY',
        'PRE_ASSIST_AMBULATORY_W_ASSIST',
        'PRE_ASSIST_WHEEL_CHAIR',
        'PRE_ASSIST_CLEAR',
        'PRE_ASSIST_CRACKLES',
        'PRE_ASSIST_RHONCHI',
        'PRE_ASSIST_WHEEZES',
        'PRE_ASSIST_RALES',
        'PRE_ASSIST_DISTENDID_JUGULAR_VIEW',
        'PRE_ASSIST_ASCITES',
        'PRE_ASSIST_EDEMA',
        'PRE_ASSIST_EDEMA_LOCAITON',
        'PRE_ASSIST_EDEMA_DEPTH',
        'PRE_ASSSIT_REGULAR',
        'PRE_ASSIST_IRREGULAR',
        'PRE_ASSIST_CONSCIOUS',
        'PRE_ASSIST_COHERENT',
        'PRE_ASSIST_DISORIENTED',
        'PRE_ASSIST_DROWSY',
        'POST_ASSIST_AMBULATORY',
        'POST_ASSIST_AMBULATORY_W_ASSIST',
        'POST_ASSIST_WHEEL_CHAIR',
        'POST_ASSIST_CLEAR',
        'POST_ASSIST_CRACKLES',
        'POST_ASSIST_RHONCHI',
        'POST_ASSIST_WHEEZES',
        'POST_ASSIST_RALES',
        'POST_ASSIST_DISTENDID_JUGULAR_VIEW',
        'POST_ASSIST_ASCITES',
        'POST_ASSIST_EDEMA',
        'POST_ASSIST_EDEMA_LOCAITON',
        'POST_ASSIST_EDEMA_DEPTH',
        'POST_ASSSIT_REGULAR',
        'POST_ASSIST_IRREGULAR',
        'POST_ASSIST_CONSCIOUS',
        'POST_ASSIST_COHERENT',
        'POST_ASSIST_DISORIENTED',
        'POST_ASSIST_DROWSY',
        'CANNULCATED_BY',
        'NO_OF_ATTEMPT',
        'ARTERIAL',
        'ARTERIAL_G',
        'VENOUS',
        'VENOUS_G',
        'EPO_GIVEN_YES',
        'EPO_GIVEN_REMARKS',
        'NEPHROLOGIST',
        'SPECIAL_ENDORSEMENT',
        'DIAGNOSIS',
        'STANDING_ORDER',
        'STATUS',
        'STATUS_DATE'   
    ];
}
